/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamsRouteImport } from './routes/_app.teams'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppObjectivesRouteImport } from './routes/_app.objectives'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppObjectivesRoute = AppObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/notifications': typeof AppNotificationsRoute
  '/objectives': typeof AppObjectivesRoute
  '/settings': typeof AppSettingsRoute
  '/teams': typeof AppTeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/notifications': typeof AppNotificationsRoute
  '/objectives': typeof AppObjectivesRoute
  '/settings': typeof AppSettingsRoute
  '/teams': typeof AppTeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/objectives': typeof AppObjectivesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/teams': typeof AppTeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/callback'
    | '/login'
    | '/register'
    | '/admin'
    | '/dashboard'
    | '/feedback'
    | '/notifications'
    | '/objectives'
    | '/settings'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/callback'
    | '/login'
    | '/register'
    | '/admin'
    | '/dashboard'
    | '/feedback'
    | '/notifications'
    | '/objectives'
    | '/settings'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/auth/callback'
    | '/login'
    | '/register'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_app/notifications'
    | '/_app/objectives'
    | '/_app/settings'
    | '/_app/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/objectives': {
      id: '/_app/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof AppObjectivesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppObjectivesRoute: typeof AppObjectivesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamsRoute: typeof AppTeamsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppObjectivesRoute: AppObjectivesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamsRoute: AppTeamsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
